// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESB.Domain.Entities
{
    public partial class Bomberos
    {
        public Bomberos()
        {
            RegistroIncendios = new HashSet<RegistroIncendios>();
        }
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public virtual ICollection<RegistroIncendios> RegistroIncendios { get; set; }
    }
}